/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as PdvRouteImport } from './routes/pdv'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsumosRouteImport } from './routes/insumos'
import { Route as FestivalRouteImport } from './routes/festival'
import { Route as IndexRouteImport } from './routes/index'

const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const PdvRoute = PdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsumosRoute = InsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalRoute = FestivalRouteImport.update({
  id: '/festival',
  path: '/festival',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/festival': typeof FestivalRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/pdv': typeof PdvRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/festival': typeof FestivalRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/pdv': typeof PdvRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/festival': typeof FestivalRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/pdv': typeof PdvRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/festival' | '/insumos' | '/login' | '/pdv' | '/receitas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/festival' | '/insumos' | '/login' | '/pdv' | '/receitas'
  id:
    | '__root__'
    | '/'
    | '/festival'
    | '/insumos'
    | '/login'
    | '/pdv'
    | '/receitas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FestivalRoute: typeof FestivalRoute
  InsumosRoute: typeof InsumosRoute
  LoginRoute: typeof LoginRoute
  PdvRoute: typeof PdvRoute
  ReceitasRoute: typeof ReceitasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdv': {
      id: '/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insumos': {
      id: '/insumos'
      path: '/insumos'
      fullPath: '/insumos'
      preLoaderRoute: typeof InsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival': {
      id: '/festival'
      path: '/festival'
      fullPath: '/festival'
      preLoaderRoute: typeof FestivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FestivalRoute: FestivalRoute,
  InsumosRoute: InsumosRoute,
  LoginRoute: LoginRoute,
  PdvRoute: PdvRoute,
  ReceitasRoute: ReceitasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
